# Site settings
title: Do not fish!
description: > # this means to ignore newlines until "baseurl:"
  Do not fish, bitch!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://donot.fish" # the base hostname & protocol for your site
twitter_username: mttlgl

# Build settings
markdown: kramdown
